# Generated by Django 3.2.13 on 2022-07-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lembrete',
            name='id_user',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
